### ISSUE TITLE
Remove `quay.io/pbench/` references in Docker files

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/visualizers#3]
Remove `quay.io/pbench/` references in Docker files.

See https://github.com/distributed-system-analysis/visualizers/blob/main/DockerfilePostPCP#L2 and https://github.com/distributed-system-analysis/visualizers/blob/main/DockerfilePostProm#L2.

**Comment by Maxusmusti** [comment]
Fixed now in [this commit](https://github.com/distributed-system-analysis/visualizers/commit/aab3bd86e7eb3fced560beac7329f54fed73ef49)
